DROP TABLE IF EXISTS products;
CREATE TABLE IF NOT EXISTS products(
   product_id        INTEGER  NOT NULL PRIMARY KEY 
  ,product_name      VARCHAR(60) NOT NULL
  ,short_description VARCHAR(100) NOT NULL
  ,no_pictures       INTEGER  NOT NULL
  ,brand_id          INTEGER  NOT NULL
  ,price             NUMERIC(6,2) NOT NULL
  ,wireless          BOOLEAN  NOT NULL
  ,wired             BOOLEAN  NOT NULL
  ,earbuds           BOOLEAN  NOT NULL
  ,gaming            BOOLEAN  NOT NULL
  ,sport             BOOLEAN  NOT NULL
  ,bluetooth         BOOLEAN  NOT NULL
  ,url               VARCHAR(200) NOT NULL
);
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (1,'RAZER HAMMERHEAD TRUE WIRELESS 2019','True Wireless Earbuds',5,1,169.9,TRUE,FALSE,TRUE,FALSE,FALSE,TRUE,'https://www.razer.com/sg-en/mobile-earphones/Razer-Hammerhead-True-Wireless-Earbuds/RZ12-02970100-R3A1?gclid=CjwKCAjw7rWKBhAtEiwAJ3CWLGXp6w_2vY1tLKEHL_rr1XRWyBETKSA_LBu7JP9SrNQ0-naDSuk_URoC-ycQAvD_BwE');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (2,'Razer Kraken Kitty - Black','Razer Kitty Ear USB Headset with Chroma',2,1,239.9,FALSE,TRUE,FALSE,TRUE,FALSE,FALSE,'https://www.razer.com/sg-en/gaming-headsets/Razer-Kraken-Kitty/RZ04-02980100-R3M1?gclid=CjwKCAjw7rWKBhAtEiwAJ3CWLOX2YeLTmEeq4phhjCtFm0ckTVG0f00KovjDrgqFKnp8cs3RNbAybxoC1LQQAvD_BwE');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (3,'Razer Hammerhead Duo Console - Green','Dual Driver In-Ears',5,1,79.9,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,'https://www.razer.com/sg-en/gaming-earphones/Razer-Hammerhead-Duo/RZ12-03030300-R3M1?gclid=CjwKCAjw7rWKBhAtEiwAJ3CWLE8uTpQT92S-2FqOz206Ai8CgVDCIIufM_4vD5kqMrjYx-RNIln7iRoCCaUQAvD_BwE');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (4,'Razer Kaira Pro for Xbox - White','Wireless Headset for Xbox Series X and mobile Xbox gaming',4,1,229.9,TRUE,FALSE,FALSE,TRUE,FALSE,TRUE,'https://www.razer.com/sg-en/console-headsets/Razer-Kaira-Pro-for-Xbox/RZ04-03470300-R3M1');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (5,'Beats Flex - Black','BEATS FLEX: FLEX ALL DAY',5,2,99.99,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,'https://www.beatsbydre.com/sg/earphones/beats-flex?sku=MYMC2');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (6,'PowerBeats Pro - Red','POWERBEATS PRO: POWER. PLAY.',4,2,328,TRUE,FALSE,TRUE,FALSE,TRUE,TRUE,'https://www.beatsbydre.com/sg/earphones/powerbeats-pro?sku=MXYA2');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (7,'Beats Solo Pro - Ivory','NOISE CANCELLING WIRELESS HEADPHONES TO STAY INSPIRED',6,2,429,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,'https://www.beatsbydre.com/sg/headphones/solo-pro?sku=MRJ72');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (8,'Beats EP - blue','WIRED HEADPHONES BUILT FOR LIFE',5,2,138,FALSE,TRUE,FALSE,TRUE,FALSE,FALSE,'https://www.beatsbydre.com/sg/headphones/beats-ep?sku=ML9D2');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (9,'PowerBeats - White','LIGHTWEIGHT WIRELESS EARPHONES FOR ALL‑DAY ACTIVITY',4,2,199,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,'https://www.beatsbydre.com/sg/products');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (10,'WF-1000XM4 Wireless Noise Cancelling Headphones','Your sound. Nothing else.',5,3,379,TRUE,FALSE,TRUE,FALSE,TRUE,TRUE,'https://www.sony.com.sg/electronics/truly-wireless/wf-1000xm4');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (11,'WF-SP900 Sports Wireless Headphones','Music to take you further',3,3,399,TRUE,FALSE,TRUE,FALSE,TRUE,TRUE,'https://www.sony.com.sg/electronics/truly-wireless/wf-sp900');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (12,'WI-1000XM2 Wireless Noise Cancelling In-ear Headphones','Only music. Nothing else.',7,3,449,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,'https://www.sony.com.sg/electronics/in-ear-headphones/wi-1000xm2');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (13,'IER-H500A h.ear in 2 In-ear Headphones','Compact. Colourful. Crystal-clear audio.',3,3,129,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,'https://www.sony.com.sg/electronics/in-ear-headphones/ier-h500a');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (14,'WH-1000XM4 Wireless Noise Cancelling Headphones','Silent White',6,3,499,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,'https://www.sony.com.sg/electronics/headband-headphones/wh-1000xm4');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (15,'MDR-1AM2 Headphones','Take music anywhere',5,3,429,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,'https://www.sony.com.sg/electronics/headband-headphones/mdr-1am2');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (16,'ARCTIS PRO WIRELESS - black','High fidelity audio comes to gaming for the first time',4,4,369.99,TRUE,FALSE,FALSE,TRUE,FALSE,TRUE,'https://steelseries.com/gaming-headsets/arctis-pro-wireless?color=black');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (17,'TUSQ','In-ear mobile gaming headset',4,4,39.9,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,'https://steelseries.com/gaming-headsets/tusq');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (18,'ARCTIS PRO - black','Peerless High Resolution PC Gaming Headset',4,4,199.99,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,'https://steelseries.com/gaming-headsets/arctis-pro');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (19,'ARCTIS 5','Design Exclusively for PC Gaming',5,4,99.99,FALSE,TRUE,FALSE,TRUE,FALSE,TRUE,'https://steelseries.com/gaming-headsets/arctis-5?color=black');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (20,'Bose Frames Soprano-black','Nothing in or on your ears',6,5,224,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,'https://www.bose.com/en_us/products/frames/bose-frames-soprano.html#v=bose_frames_soprano_black');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (21,'Bose Sport Open Earbuds','HEAR THE MUSIC.AND THE MOMENT.',6,5,199,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,'https://www.bose.com/en_us/products/headphones/earbuds/sport-open-earbuds.html#v=sport_open_earbuds_black');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (22,'Bose Noise Cancelling Headphones 700 - black','PREMIUM QUIET. BOLD SOUND.',6,5,419,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,'https://www.bose.com/en_us/products/headphones/noise_cancelling_headphones/noise-cancelling-headphones-700-charging-case-pkg.html#v=noise_cancelling_headphones_700_charging_case_pkg_black');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (23,'Bose QuietComfort® Earbuds','RULE THE QUIET',6,5,279,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,'https://www.bose.com/en_us/products/headphones/earbuds/quietcomfort-earbuds.html#v=qc_earbuds_stone_blue');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (24,'SoundSport wireless headphones','Engineered to push you forward, not hold you back',3,5,129,FALSE,TRUE,TRUE,FALSE,TRUE,TRUE,'https://www.bose.com/en_us/products/headphones/earbuds/soundsport-wireless.html#v=soundsport_wireless_aqua');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (25,'Bose QuietComfort® 35 II Gaming Headset​','2-in-1 gaming and lifestyle headset with acclaimed lifelike sound',6,5,329,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,'https://www.bose.com/en_us/products/headphones/gaming_headset/quietcomfort-35-gaming-headset.html#v=qc35_ii_gaming_black');
INSERT INTO products(product_id,product_name,short_description,no_pictures,brand_id,price,wireless,wired,earbuds,gaming,sport,bluetooth,url) VALUES (26,'SoundComm B40 Headset','A professional communication headset',6,5,849,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,'https://www.bose.com/en_us/products/headphones/professional_communications/soundcomm-b40-headset.html');
