DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users(
   user_id    INT  NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,email      VARCHAR(50) NOT NULL
  ,password   VARCHAR(50) NOT NULL
  ,first_name VARCHAR(50) NOT NULL
  ,last_name  VARCHAR(50) NOT NULL
  ,contact    VARCHAR(10) NOT NULL
);
